### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by devil233-ui** [1umine/lagrange-plugin#1]
系统ub22，崽是trss3.13
全程没看到没有报依赖缺失之类的
> [19:10:53.779][ERRO][unhandled.] Error: Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?
    at exports.decode (/root/TRSS_AllBot/TRSS-Yunzai/node_modules/.pnpm/tar-stream@1.6.2/node_modules/tar-stream/headers.js:267:43)
    at TarUncompressStream.onheader (/root/TRSS_AllBot/TRSS-Yunzai/node_modules/.pnpm/tar-stream@1.6.2/node_modules/tar-stream/extract.js:124:39)
    at Extract._write (/root/TRSS_AllBot/TRSS-Yunzai/node_modules/.pnpm/tar-stream@1.6.2/node_modules/tar-stream/extract.js:250:8)
    at doWrite (/root/TRSS_AllBot/TRSS-Yunzai/node_modules/.pnpm/readable-stream@2.3.8/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/root/TRSS_AllBot/TRSS-Yunzai/node_modules/.pnpm/readable-stream@2.3.8/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/root/TRSS_AllBot/TRSS-Yunzai/node_modules/.pnpm/readable-stream@2.3.8/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at ReadStream.ondata (node:internal/streams/readable:1007:22)
    at ReadStream.emit (node:events:507:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3) {
  [stack]: [Getter/Setter: 'Error: Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?\n' +
    '    at exports.decode (/root/TRSS_AllBot/TRSS-Yunzai/node_modules/.pnpm/tar-stream@1.6.2/node_modules/tar-stream/headers.js:267:43)\n' +
    '    at TarUncompressStream.onheader (/root/TRSS_AllBot/TRSS-Yunzai/node_modules/.pnpm/tar-stream@1.6.2/node_modules/tar-stream/extract.js:124:39)\n' +
    '    at Extract._write (/root/TRSS_AllBot/TRSS-Yunzai/node_modules/.pnpm/tar-stream@1.6.2/node_modules/tar-stream/extract.js:250:8)\n' +
    '    at doWrite (/root/TRSS_AllBot/TRSS-Yunzai/node_modules/.pnpm/readable-stream@2.3.8/node_modules/readable-stream/lib/_stream_writable.js:428:64)\n' +
    '    at writeOrBuffer (/root/TRSS_AllBot/TRSS-Yunzai/node_modules/.pnpm/readable-stream@2.3.8/node_modules/readable-stream/lib/_stream_writable.js:417:5)\n' +
    '    at Writable.write (/root/TRSS_AllBot/TRSS-Yunzai/node_modules/.pnpm/readable-stream@2.3.8/node_modules/readable-stream/lib/_stream_writable.js:334:11)\n' +
    '    at ReadStream.ondata (node:internal/streams/read'... 188 more characters],
  [message]: 'Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?'
}

**Comment by 1umine** [comment]
可能下载没完全下载好吧，删了 `data/lagrange-plugin` 重新启动试试，实在不行就自己手动到 https://github.com/LagrangeDev/Lagrange.Core/releases/tag/nightly 下载解压出可执行文件并移动重命名到  `data/lagrange-plugin/run/lagrange.bin`
> Linux 系统没测试过 （

**Comment by devil233-ui** [comment]
手动了，然而它还是识别不到![image](https://github.com/user-attachments/assets/81f63a1a-28c3-4de2-acc3-6817ed7ef90d)
0|TRSS-Yun | [23:32:23.831][ERRO][  TRSSYz  ] 解压 https://mirror.ghproxy.com/https://github.com/LagrangeDev/Lagrange.Core/releases/download/nightly/Lagrange.OneBot_linux-x64_net8.0_SelfContained.tar.gz 失败，可能下载文件损坏，请尝试手动下载并将可执行文件放到 
0|TRSS-Yun |       ./data/lagrange-plugin/run 目录下并重命名为 ./data/lagrange-plugin/run/lagrange.bin, 并赋予执行权限(对于linux系统)
0|TRSS-Yun | [23:32:23.832][WARN][  TRSSYz  ] 
0|TRSS-Yun | 
0|TRSS-Yun | 
0|TRSS-Yun | 
0|TRSS-Yun | 首次登陆需要扫码，请扫描 /root/TRSS-Yunzai/data/lagrange-plugin/run 下 qr-0.png 进行扫码登陆 bot
0|TRSS-Yun | 
0|TRSS-Yun | 
0|TRSS-Yun | 
0|TRSS-Yun | 
0|TRSS-Yun | [23:32:23.835][ERRO][unhandled.] Error: ENOENT: no such file or directory, lstat '/root/TRSS-Yunzai/data/lagrange-plugin/run/lagrange.bin'
0|TRSS-Yun |     at Object.realpathSync (node:fs:2729:29)
0|TRSS-Yun |     at startLagrange (file:///root/TRSS-Yunzai/plugins/lagrange-plugin/apps/lagrange/lagrange.js:39:17)
0|TRSS-Yun |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
0|TRSS-Yun |   [stack]: "Error: ENOENT: no such file or directory, lstat '/root/TRSS-Yunzai/data/lagrange-plugin/run/lagrange.bin'\n" +
0|TRSS-Yun |     '    at Object.realpathSync (node:fs:2729:29)\n' +
0|TRSS-Yun |     '    at startLagrange (file:///root/TRSS-Yunzai/plugins/lagrange-plugin/apps/lagrange/lagrange.js:39:17)\n' +
0|TRSS-Yun |     '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
0|TRSS-Yun |   [message]: "ENOENT: no such file or directory, lstat '/root/TRSS-Yunzai/data/lagrange-plugin/run/lagrange.bin'",
0|TRSS-Yun |   errno: -2,
0|TRSS-Yun |   code: 'ENOENT',
0|TRSS-Yun |   syscall: 'lstat',
0|TRSS-Yun |   path: '/root/TRSS-Yunzai/data/lagrange-plugin/run/lagrange.bin'
0|TRSS-Yun | }

**Comment by 1umine** [comment]
小写 `lagrange.bin`

**Comment by devil233-ui** [comment]
连上了，但出现了一堆奇奇怪怪警告
不过好像基本功能都挺正常的，那就不管了吧（
>0|TRSS-Yunzai  | warn: Lagrange.Core.BotContext[0]
0|TRSS-Yunzai  |       [2024-11-22 23:51:07] [BusinessContext] [WARNING]: Error when processing the event: Lagrange.Core.Internal.Event.System.FetchCookieEvent
0|TRSS-Yunzai  | warn: Lagrange.Core.BotContext[0]
0|TRSS-Yunzai  |       [2024-11-22 23:51:07] [BusinessContext] [WARNING]: System.ArgumentNullException: Value cannot be null. (Parameter 'source')
0|TRSS-Yunzai  |          at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
0|TRSS-Yunzai  |          at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
0|TRSS-Yunzai  |          at Lagrange.Core.Internal.Service.System.FetchCookieService.Parse(Span`1 input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, FetchCookieEvent& output, List`1& extraEvents)
0|TRSS-Yunzai  |          at Lagrange.Core.Internal.Service.BaseService`1.Lagrange.Core.Internal.Service.IService.Parse(Span`1 input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, ProtocolEvent& output, List`1& ext
0|TRSS-Yunzai  | raEvents)
0|TRSS-Yunzai  |          at Lagrange.Core.Internal.Context.ServiceContext.ResolveEventByPacket(SsoPacket packet)
0|TRSS-Yunzai  |          at Lagrange.Core.Internal.Context.BusinessContext.SendEvent(ProtocolEvent event)
0|TRSS-Yunzai  | warn: Lagrange.OneBot.Core.Operation.OperationService[0]
0|TRSS-Yunzai  |       Unexpected error encountered while handling message.
0|TRSS-Yunzai  |       System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
0|TRSS-Yunzai  |          at System.Collections.Generic.List`1.get_Item(Int32 index)
0|TRSS-Yunzai  |          at Lagrange.OneBot.Core.Operation.Generic.GetCookiesOperation.HandleOperation(BotContext context, JsonNode payload)
0|TRSS-Yunzai  |          at Lagrange.OneBot.Core.Operation.OperationService.HandleOperation(MsgRecvEventArgs e)
0|TRSS-Yunzai  | [23:51:12.711][MARK][1400606839] OneBotv11(QQ) Lagrange.OneBot v0.0.3 已连接

**Comment by 1umine** [comment]
警告正常，能用就行（

**Comment by devil233-ui** [comment]
看到你把解压缩修了我就试了下，不过是不是还漏了移动重命名这步（
![image](https://github.com/user-attachments/assets/718c0a8d-4c3b-4c51-8357-358f36fd4294)

**Comment by 1umine** [comment]
> 看到你把解压缩修了我就试了下，不过是不是还漏了移动重命名这步（
> ![image](https://github.com/user-attachments/assets/718c0a8d-4c3b-4c51-8357-358f36fd4294)
> 

没有吧，只是解压那一步出了问题

**Comment by devil233-ui** [comment]
![image](https://github.com/user-attachments/assets/57fecb3a-374d-4074-bae2-8cdaf9001b33)
这看着是找执行文件找错路径了

**Comment by 1umine** [comment]
> ![image](https://github.com/user-attachments/assets/57fecb3a-374d-4074-bae2-8cdaf9001b33)
> 这看着是找执行文件找错路径了

找到问题了，大小写错误，~~被windows忽略大小写坑了没测出来~~，有时间修一下（
